"""Embed signatures produced by the matching L^ tooling host, then rebuild the extension."""
import argparse
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import time

ROOT = Path(__file__).resolve().parents[1]

def run(*args, **kwargs):
    subprocess.run(list(map(str, args)), check=True, timeout=180, **kwargs)

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--host', type=Path, help='Full eos_lhat_host executable (defaults to the build directory)')
    p.add_argument('--build', type=Path, default=ROOT / 'build')
    p.add_argument('--sdk', type=Path, default=ROOT / 'EOSSDK/SDK')
    p.add_argument('--config', default='Release')
    a = p.parse_args()
    host = a.host or next(x for x in [a.build / 'tools' / a.config / 'eos_lhat_host.exe', a.build / 'tools' / 'eos_lhat_host'] if x.exists())
    suffix = '.dll' if sys.platform == 'win32' else '.dylib' if sys.platform == 'darwin' else '.so'
    candidates = [a.build / a.config / ('eos_lhat' + suffix), a.build / ('eos_lhat' + suffix)]
    library = next((x for x in candidates if x.exists()), None)
    if not library:
        raise SystemExit('Build eos_lhat first')
    with tempfile.TemporaryDirectory(prefix='eos-signatures-') as tmp:
        work = Path(tmp)
        shutil.copy2(library, work / library.name)
        for dep in (a.sdk / 'Bin').glob('*' + suffix):
            shutil.copy2(dep, work / dep.name)
        binary = work / 'signatures.bin'
        env = dict(os.environ)
        loader_path = 'PATH' if sys.platform == 'win32' else 'DYLD_LIBRARY_PATH' if sys.platform == 'darwin' else 'LD_LIBRARY_PATH'
        env[loader_path] = str(work) + os.pathsep + env.get(loader_path, '')
        run(host.resolve(), 'signatures', work / library.name, binary, env=env, cwd=work)
        data = binary.read_bytes()
        header = a.build / 'generated/eos_signatures.h'
        # Make 3.81 (macOS) compares whole-second mtimes; an object built in the
        # same second as the header would be considered up to date.
        newest = max((x.stat().st_mtime for x in a.build.rglob('*') if x.suffix in ('.o', '.obj')), default=0)
        while time.time() < int(newest) + 1:
            time.sleep(0.05)
        lines = [', '.join(f'0x{x:02x}' for x in data[n:n+16]) + ',' for n in range(0, len(data), 16)]
        header.write_text('// Generated by scripts/embed-signatures.py; do not edit.\n'
                          'static const unsigned char eos_signatures[] = {\n' + '\n'.join(lines) +
                          '\n};\nstatic const size_t eos_signatures_length = sizeof(eos_signatures);\n', encoding='utf-8')
    run('cmake', '--build', a.build, '--config', a.config)
    print('Embedded signatures and rebuilt eos_lhat')

if __name__ == '__main__':
    main()
