"""Embed signatures produced by a matching full LÔVE host, then rebuild the extension."""
import argparse
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]

def run(*args, **kwargs):
    subprocess.run(list(map(str, args)), check=True, timeout=180, **kwargs)

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--lovec', type=Path, default=ROOT.parent / 'lhat-love/build/love/Release/lovec.exe')
    p.add_argument('--build', type=Path, default=ROOT / 'build')
    p.add_argument('--sdk', type=Path, default=ROOT / 'EOSSDK/SDK')
    p.add_argument('--config', default='Release')
    a = p.parse_args()
    suffix = '.dll' if sys.platform == 'win32' else '.dylib' if sys.platform == 'darwin' else '.so'
    candidates = [a.build / a.config / ('eos_lhat' + suffix), a.build / ('eos_lhat' + suffix)]
    library = next((x for x in candidates if x.exists()), None)
    if not library:
        raise SystemExit('Build eos_lhat first')
    with tempfile.TemporaryDirectory(prefix='eos-signatures-') as tmp:
        game = Path(tmp)
        shutil.copy2(library, game / library.name)
        for dep in (a.sdk / 'Bin').glob('*' + suffix):
            shutil.copy2(dep, game / dep.name)
        (game / 'extensions.txt').write_text('eos_lhat\n', encoding='utf-8')
        (game / 'main.lh').write_text('module^signatureProbe\nimport^eos\npublic^let^run = p^{ return^0 }\n', encoding='utf-8')
        (game / 'conf.lton').write_text('window = false^, modules = {audio = false^, graphics = false^}', encoding='utf-8')
        binary = game / 'signatures.bin'
        env = dict(os.environ)
        env['PATH'] = str(game) + os.pathsep + env.get('PATH', '')
        run(a.lovec.resolve(), '--no-error-screen', '--dump-signatures', binary, game, env=env, cwd=game)
        data = binary.read_bytes()
        header = a.build / 'generated/eos_signatures.h'
        lines = [', '.join(f'0x{x:02x}' for x in data[n:n+16]) + ',' for n in range(0, len(data), 16)]
        header.write_text('// Generated by scripts/embed-signatures.py; do not edit.\n'
                          'static const unsigned char eos_signatures[] = {\n' + '\n'.join(lines) +
                          '\n};\nstatic const size_t eos_signatures_length = sizeof(eos_signatures);\n', encoding='utf-8')
    run('cmake', '--build', a.build, '--config', a.config)
    print('Embedded signatures and rebuilt eos_lhat')

if __name__ == '__main__':
    main()
